webapp/src/main/webapp/index.jsp

added feature

---

Dockerfile

Update dockerfile on Dev
S02-158
None

S02-158. Update dockerfile on Dev

---

Dockerfile

Kelly update dockerfile of Dev pipeline
S02-164.

S02-164. Kelly update dockerfile of Dev pipeline

---

Dockerfile

updated Dockerfile with new enties
Eric update file
S2-171.
None

S2-171. Eric update file

---

Dockerfile

- [ *] (External) Interfaces documented

Feature s0 158

---

Dockerfile
Jenkinsfile

S02-168.Peter update dockerfile

---

Dockerfile

Detailed description here
gueno3update dockefile3
- [x ] Bug fix (non-breaking change that fixes an issue)
so2-166 

gueno3update dockefile3

---

Dockerfile

S02-164. Kelly-updating-Dockerfile
S02-164
None

S02-164. Kelly-updating-Dockerfile

---

Dockerfile

Update Dockerfile on Dev pipeline
S02158.
none

S02158. Ousmane  Update Dockerfile on Dev pipeline

---

Dockerfile

Update Dockerfile on Dev pipeline 
S02158. 
None

S02158. Eric-Update Dockerfile on Dev pipeline 

---

Dockerfile

S02158. Valdes-Update Dockerfile on Dev pipeline

---

simplice1
simplice2

Update Dockerfile on Dev pipeline
S02158.
None

S02158. Simplice Update Dockerfile on Dev pipeline

---

kantin2
kantin3
kantin4

S02158-kantin- my-files.

---

idrissa

Idrissa Createfile -Second change

---

nigieu_file

S02-177 nigieu Added a file

---

myself

Hop it works now

---

Dockerfile
alex1

S02-177 Alex created directories

---

a.txt
b.txt

S02-102 Duclair Added some files 

---

file1
file2

achille adding file

---

git1.sh
git4.sh
love7.sh

S0-123 serge-love devops

---

simplice1
simplice2

Reverts devopseasylearning/SESSION-01-DEVELOPMENT#94

"S02-158. Simplice Update Dockerfile on Dev pipeline"

---

barby01
barby02

S02-177 Barbara updated new files
Barbara updated new files
S02-177 
none

S02-177 Barbara updated new files

---

jeanne

file jeanne created

---

alfred

S02-144 Alfred-Adding Newfiles

---

sinclair

sinclair created a new file
S02158.

S02158. sinclair created a new file on Dev pipeline

---

adele.txt
adele1.txt
adele2.txt

S02-158. adele added two file on Dev pipeline

---

eric1
eric2
ericos/eruccds

S02-166. Eric-update dockefile

---

DevOps_Money_Is_Coming1
DevOps_Money_Is_Coming2
DevOps_Money_Is_Coming3
DevOps_Money_Is_Coming4
DevOps_Money_Is_Coming5
DevOps_Money_Is_Coming6
DevOps_Money_Is_Coming7
DevOps_Money_Is_Coming8
DevOps_Money_Is_Coming9
cedric1
cedric2
cedric3

Update my app with new files
S02-158
None

S02-158. Cedric Update my app to fix bugs with 10 new files

---

Dockerfile

Update Dockerfile for Motivation

---

README.md

collaborate

---

morgane

S02 198 igor update-dockerfile

---

valdes-practice2.txt

S02-123-Valdes: creating a simple Dockerfile

---

100k/100k
100k/200k/200k
100k/200k/300k/300k
learning

S02-177 Alex created files and directories

---

yvan-Dockerfile
yvan-file

> update file
- [x ] New feature (non-breaking change that adds functionality)
> 158
> None

S02-158-yvan update file

---

lucy-feature-b

- [ X] New feature (non-breaking change that adds functionality)

thanks guys

---

Pauly1
pauly1

I am adding to the existing code

---

lucy-feature-b

SO2-#200 Lucy-feature-b

---

anipal

Happy Sunday and Happy Father's day to all father out there

---

igorgit-test

S02-233 igor training

---

joanie

Dockerfile test
S0-233 Dockerfile test

S0-233 igor one.more .try

---

valdes/valdesdockerfile

#This is a try with a class simple dockerfile
None

S02-112-Valdes: This is a try with a class simple dockerfile

---

joel3

 adding a file
